#
# Makefile 
#

#Flags used to compile files
CFLAGS = -g -Wall -Werror -O2 -lm 

#Compile
CC=gcc

#Deps
DEPS=estrutura.h operacoes.h entrada.h 

#Name of the executable file
TARGET=prog

#Files
PROG1 = main.c operacoes.c entrada.c
OBJ = main.o operacoes.o entrada.o

all: $(TARGET)

%.o: %.c $(DEPS)
	$(CC) $(CFLAGS) -c -o $@ $<

$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^ -lm 

clean:
	rm -f $(TARGET) *.o
